// User types
export const GET_ERRORS ='GET_ERRORS';
export const CLEAR_ERRORS ='CLEAR_ERRORS';
export const SET_CURRENT_USER ='SET_CURRENT_USER';
export const SET_CURRENT_USER_INFO ='SET_CURRENT_USER_INFO';
export const CLEAR_CURRENT_USER_INFO ='CLEAR_CURRENT_USER_INFO';

// Profile types
export const GET_PROFILE ='GET_PROFILE';
export const PROFILE_LOADING ='PROFILE_LOADING';
export const PROFILE_NOT_FOUND ='PROFILE_NOT_FOUND';
export const CLEAR_CURRENT_PROFILE ='CLEAR_CURRENT_PROFILE';
export const GET_PROFILES ='GET_PROFILES';
export const GET_CUSTOM_PROFILES ='GET_CUSTOM_PROFILES';

// Admin types
export const GET_ALL_TUTORS = 'GET_ALL_TUTORS';
export const GET_ALL_PARENTS = 'GET_ALL_PARENTS';
export const CLEAR_ALL_TUTORS = 'CLEAR_ALL_TUTORS';
export const CLEAR_ALL_PARENTS = 'GET_ALL_PARENTS';
